meta_title: "ADCREW | INFLUENCE & STRATEGY"
meta_description: "ADCREW est une agence parisienne spécialisée dans le marketing d’influence."
meta_image: "logo-tag.jpeg" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
